language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
os:
  - linux
before_install: npm install
before_script: chmod 0777 ./node_modules/.bin/mocha
after_script: grunt test:browser
after_script: istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
